#!/usr/bin/env bash
# discover-schema.sh — produce a single human-readable summary of every
# table + index across the three analytics databases. Reads the
# refinery migration files from migrations/{ordinals,ordinals-brc20,runes}/
# and concatenates the CREATE statements grouped by db, sorted by version.
#
# Output: schema-verification/schema-summary.md (markdown), and a flat
# list of (db, table) pairs to schema-verification/tables.txt.
#
# No external deps beyond awk + sed + sort + bash. Safe to run anywhere
# the bitcoin-indexer repo is checked out.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
MIGRATIONS="$REPO_ROOT/migrations"

OUT_MD="$SCRIPT_DIR/schema-summary.md"
OUT_TABLES="$SCRIPT_DIR/tables.txt"

if [[ ! -d "$MIGRATIONS" ]]; then
    echo "discover-schema: migrations dir not found at $MIGRATIONS" >&2
    exit 1
fi

# Sort migration files by their refinery version prefix (V1, V2, ... V19).
# Plain glob sort would put V10 before V2.
sort_versioned() {
    # input: paths on stdin, output: paths sorted by V<N>
    awk -F'/' '{ print $NF }' \
        | awk 'match($0, /^V([0-9]+)__/, m) { print m[1]"\t"$0 }' \
        | sort -k1,1n \
        | cut -f2-
}

emit_db() {
    local db="$1"
    local dir="$MIGRATIONS/$db"
    [[ -d "$dir" ]] || { echo "skip: $dir (missing)"; return; }

    printf '\n## %s\n\n' "$db"

    # Iterate in version order
    while IFS= read -r fname; do
        local f="$dir/$fname"
        [[ -f "$f" ]] || continue
        printf '### %s\n\n```sql\n' "$fname"
        cat "$f"
        printf '```\n\n'
        # Extract table names from CREATE TABLE for tables.txt. Many
        # migration files only ALTER existing tables (charms, parents,
        # block_hash) — grep returning no match is fine, suppress its
        # exit code so set -e + pipefail don't abort us.
        local matches
        matches="$(grep -iE '^[[:space:]]*CREATE TABLE' "$f" || true)"
        if [[ -n "$matches" ]]; then
            printf '%s\n' "$matches" \
                | sed -E 's/^[[:space:]]*CREATE TABLE[[:space:]]+(IF NOT EXISTS[[:space:]]+)?([A-Za-z_][A-Za-z0-9_]*).*/\2/I' \
                | while read -r tbl; do
                    [[ -n "$tbl" ]] && printf '%s\t%s\n' "$db" "$tbl" >> "$OUT_TABLES.tmp"
                  done
        fi
    done < <(ls "$dir" | grep -E '^V[0-9]+__.*\.sql$' | sort_versioned)
}

# Reset outputs
: > "$OUT_TABLES.tmp"
{
    printf '# bitcoin-indexer postgres schema summary\n\n'
    printf 'Generated by `discover-schema.sh` from `migrations/`.\n'
    printf 'Source of truth — do not hand-edit. Re-run the script after\n'
    printf 'a migration changes.\n'

    for db in ordinals ordinals-brc20 runes; do
        emit_db "$db"
    done
} > "$OUT_MD"

sort -u "$OUT_TABLES.tmp" > "$OUT_TABLES"
rm -f "$OUT_TABLES.tmp"

echo "wrote $OUT_MD"
echo "wrote $OUT_TABLES ($(wc -l < "$OUT_TABLES") tables)"
